# Site settings
title: PipelineDP
description: >-
  Write fast, flexible pipelines that use modern techniques to
  aggregate user data in a privacy-preserving manner.
baseurl: ""
url: "https://pipelinedp.io"
twitter_username: openminedorg
github_repository: OpenMined/PipelineDP

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed
